# 注册 Windows 计划任务，登录时把 WSL 发行版拉起来。
#
#   powershell -ExecutionPolicy Bypass -File deploy\register-startup-task.ps1
#   powershell -ExecutionPolicy Bypass -File deploy\register-startup-task.ps1 -Remove
#
# 为什么还需要这一步：systemd unit 只管「WSL 起来之后」的事，而 WSL 发行版本身
# 不随 Windows 开机启动——不碰它就永远不启动，enable 过的服务也不会跑。这个任务
# 只做一件事：执行一条最轻的 WSL 命令，把发行版发起来，剩下的交给 systemd。

param(
    [string]$Distro = "Ubuntu",
    [string]$TaskName = "quantmine-wsl-boot",
    [switch]$Remove,
    # 计划任务需要管理员；这台机器上非提权注册连子目录都会 Access denied。
    # 用启动文件夹则完全不需要任何权限，代价见下方 Install-StartupShortcut。
    [switch]$StartupFolder
)

$ErrorActionPreference = "Stop"

$startupCmd = Join-Path ([Environment]::GetFolderPath('Startup')) "quantmine-wsl-boot.cmd"

function Test-Elevated {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    (New-Object Security.Principal.WindowsPrincipal $id).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Install-StartupShortcut {
    # 启动文件夹方案：登录时执行，零权限。
    # 相比计划任务少了 StartWhenAvailable 和电池策略，但这个动作是登录触发、
    # 瞬间完成，那些设置本来也用不上。唯一可见差别是会闪一下控制台窗口。
    param([string]$Distro, [string]$LogPath)

    # 生成的 .cmd 刻意全 ASCII 且显式 CRLF，两点都是踩过的坑：
    #  - 批处理必须 CRLF。本 .ps1 自身是 LF 换行，here-string 会把 LF 原样带进
    #    生成物，cmd.exe 于是把整个文件当一行乱切，每次登录蹦两条
    #    "'xxx' is not recognized"。
    #  - 中文注释按控制台代码页落盘（中文系统是 GBK），换个代码页又会坏一次。
    #    说明文字留在本脚本里即可，生成物不需要。
    $lines = @(
        '@echo off',
        'rem quantmine: wake WSL at logon; systemd inside starts the services.',
        'rem Generated by deploy\register-startup-task.ps1 -StartupFolder',
        ('wsl.exe -d {0} -- /bin/true >> "{1}" 2>&1' -f $Distro, $LogPath)
    )
    [IO.File]::WriteAllText($startupCmd, ($lines -join "`r`n") + "`r`n",
                            [Text.Encoding]::ASCII)
    Write-Host "已写入启动项：$startupCmd"
    Write-Host "登录时会闪一下控制台窗口，属正常。"
}

if ($Remove) {
    # 两种机制都清，省得回头还要记当初装的是哪一个
    $found = $false
    if (Test-Path $startupCmd) {
        Remove-Item $startupCmd -Force
        Write-Host "已删除启动项 $startupCmd"
        $found = $true
    }
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "已删除计划任务 $TaskName"
        $found = $true
    }
    if (-not $found) { Write-Host "两种机制都未安装，无需清理" }
    exit 0
}

# 只需把发行版唤醒；systemd 接手后续。输出重定向到日志，否则 wsl.exe 本身的失败
# （发行版损坏、被 --shutdown 等）不会留下任何痕迹。
# 唤醒日志放在 Windows 本地应用目录，不依赖项目盘是否可访问。否则日志重定向
# 本身失败时，cmd.exe 甚至不会执行后面的 wsl.exe。
$logDir = Join-Path $env:LOCALAPPDATA "QuantMine"
New-Item -ItemType Directory -Force -Path $logDir | Out-Null
$log = Join-Path $logDir "wsl-boot.log"

if ($StartupFolder) {
    Install-StartupShortcut -Distro $Distro -LogPath $log
    Write-Host "立即验证: & `"$startupCmd`""
    exit 0
}

$action = New-ScheduledTaskAction -Execute "cmd.exe" `
    -Argument "/c wsl.exe -d $Distro -- /bin/true >> `"$log`" 2>&1"

$trigger = New-ScheduledTaskTrigger -AtLogOn

# AllowStartIfOnBatteries: 默认是 $false，笔记本用电池时任务会停在 Queued 却仍然
#   报 LastTaskResult=0，看上去一切正常（备份任务上真踩过）。
# StartWhenAvailable: 错过触发时补跑。
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable -ExecutionTimeLimit ([TimeSpan]::Zero)

# Interactive 主体：只在用户登录后触发，不需要存储密码。真正的「未登录也运行」
# 要求把密码交给任务计划程序，那是另一个安全权衡，这里不默认开启。
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive

if (-not (Test-Elevated)) {
    # 直接注册会抛 HRESULT 0x80070005「拒绝访问」，而那条报错不会告诉你该怎么办。
    Write-Host "当前 PowerShell 未提权，任务计划程序会拒绝注册。两条路：" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  1) 以管理员身份重跑本脚本（和现有 quantmine-db-backup 一致的机制）："
    Write-Host "     Start-Process powershell -Verb RunAs -ArgumentList '-File','$PSCommandPath'"
    Write-Host ""
    Write-Host "  2) 改用启动文件夹，完全不需要管理员："
    Write-Host "     powershell -File `"$PSCommandPath`" -StartupFolder"
    exit 1
}

if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}
Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Settings $settings -Principal $principal `
    -Description "登录时唤醒 WSL($Distro)，由其中的 systemd 启动 quantmine 服务" | Out-Null

Write-Host "已注册计划任务 $TaskName（登录时触发）"
Write-Host "立即验证: Start-ScheduledTask -TaskName $TaskName"
Write-Host "查看状态: Get-ScheduledTaskInfo -TaskName $TaskName"
