"""Persist and display generated login credentials; shared by setup,
create_user and reset_password.

Why write a file instead of only printing: initialization output is long and
scrolls away, and deployment scripts often redirect stdout. A password exists in
plaintext only at the moment it is generated -- miss it and the only way back is
another reset, because the database stores a one-way hash. So both paths run.

Why JSON rather than plain text: the fields are structured (service, URL, user
name, password, timestamp), so adding an Airflow entry or a second user later
needs no parser change, and a text editor still renders it fine.

Entries merge on (service, username) rather than overwriting the whole file:
resetting the Airflow password must not wipe the quantmine account above it.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CREDENTIALS_PATH = ROOT / ".initial-credentials.json"

_NOTE = (
    "Login credentials generated by quantmine. Passwords are visible only at "
    "generation time; the database stores a one-way hash. Delete this file once "
    "you have signed in and changed the password. It is ignored by .gitignore -- "
    "never commit it."
)


def save_credentials(
    entries: list[dict],
    path: Path | None = None,
) -> Path:
    """Merge credentials into the JSON file and return its path.

    Args:
        entries: each holds ``service`` / ``username`` / ``password``, plus an
            optional ``url``.
        path: override the default write location; used by tests.

    Returns:
        The path actually written.
    """
    path = path or CREDENTIALS_PATH
    now = datetime.now().astimezone().isoformat(timespec="seconds")

    existing: list[dict] = []
    if path.exists():
        try:
            existing = json.loads(path.read_text(encoding="utf-8")).get(
                "credentials", []
            )
        except (json.JSONDecodeError, OSError):
            # 文件被手改坏了不该阻断重置——重置本身就是救急路径
            existing = []

    merged = {(e.get("service"), e.get("username")): e for e in existing}
    for entry in entries:
        merged[(entry["service"], entry["username"])] = {**entry, "updated_at": now}

    path.write_text(
        json.dumps(
            {
                "note": _NOTE,
                "generated_at": now,
                "credentials": list(merged.values()),
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    try:
        path.chmod(0o600)
    except OSError:
        # Windows 上 chmod 基本无效，属预期
        pass
    return path


def print_credentials(entries: list[dict], path: Path) -> None:
    """Print prominently to the console so the values can be copied on the spot."""
    if not entries:
        return
    bar = "=" * 66
    print(f"\n{bar}")
    print("  LOGIN CREDENTIALS (shown in plaintext this one time)")
    print(bar)
    for entry in entries:
        print(f"  Service:  {entry['service']}")
        if entry.get("url"):
            print(f"  URL:      {entry['url']}")
        print(f"  Username: {entry['username']}")
        print(f"  Password: {entry['password']}")
        print("  " + "-" * 62)
    print(f"  Written to: {path}")
    print("  Change the password after signing in, then delete that file.")
    print(f"{bar}\n")


def emit(entries: list[dict], path: Path | None = None) -> None:
    """Persist and print; callers normally need only this one."""
    if not entries:
        return
    print_credentials(entries, save_credentials(entries, path))
