"""Generate a local Docker Compose environment file with strong random secrets.

The output is intentionally ignored by Git and Docker's build context. Existing
files are never overwritten unless ``--force`` is supplied.
"""

from __future__ import annotations

import argparse
import base64
import os
import secrets
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = ROOT / ".env.docker"


def _token(length: int = 24) -> str:
    """Return a URL-safe password suitable for interpolation in a DB URL."""
    return secrets.token_urlsafe(length)


def render() -> str:
    fernet_key = base64.urlsafe_b64encode(os.urandom(32)).decode("ascii")
    values = {
        "POSTGRES_USER": "postgres",
        "POSTGRES_PASSWORD": _token(),
        "QUANTMINE_WEB_PASSWORD": _token(),
        "QUANTMINE_PIPELINE_PASSWORD": _token(),
        "AIRFLOW_DB_PASSWORD": _token(),
        "QUANT_AUTH_SECRET": secrets.token_hex(32),
        "QUANTMINE_ADMIN_USER": "admin",
        "QUANTMINE_ADMIN_PASSWORD": _token(18),
        "AIRFLOW_FERNET_KEY": fernet_key,
    }
    header = (
        "# Generated by scripts/create_docker_env.py.\n"
        "# Contains secrets: do not commit, paste into issues, or add to images.\n"
    )
    # Every variable in this file is forwarded into the webapi container, so an
    # AI provider only needs its key added here -- no compose edit. The name is
    # free-form: whatever is typed into AI Config's "API Key env var" field.
    ai_keys = (
        "\n"
        "# -- AI provider API keys --\n"
        "# Uncomment the ones you use, or add any other name. The value must match\n"
        "# the 'API Key env var' field of the provider in the AI Config page.\n"
        "# Recreate webapi after editing: a running container keeps its environment.\n"
        "#   docker compose --env-file .env.docker up -d webapi\n"
        "#OPENAI_API_KEY=\n"
        "#SILICONFLOW_API_KEY=\n"
        "#DEEPSEEK_API_KEY=\n"
        "#MOONSHOT_API_KEY=\n"
        "#DASHSCOPE_API_KEY=\n"
        "#ZHIPU_API_KEY=\n"
        "#OPENROUTER_API_KEY=\n"
    )
    body = "".join(f"{key}={value}\n" for key, value in values.items())
    return header + body + ai_keys


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    output = args.output.resolve()
    if output.exists() and not args.force:
        parser.error(f"refusing to overwrite existing file: {output}")
    output.write_text(render(), encoding="utf-8", newline="\n")
    try:
        output.chmod(0o600)
    except OSError:
        pass
    print(f"Docker environment written to {output}")
    print("Admin credentials are stored in that file; keep it private.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
