"""One-command initialization: create roles/databases, apply the schema, grant
privileges, initialize Airflow, write .env, and create the first administrator.
Targets personal self-hosting, where the operator is also the user.

Idempotent: safe to re-run. Existing roles, databases, tables and users are
skipped or aligned rather than destroyed. Table creation has a single source of
truth, quantmine/storage/schema.sql (IF NOT EXISTS throughout).

Superuser access (required to create roles, databases and extensions):
    1. Prefer a direct connection string (QUANTMINE_SUPERUSER_URL, default
       postgres@localhost);
    2. Fall back to `sudo -u postgres psql` (local peer auth on Linux/WSL);
    3. If neither works, print the SQL to run by hand and exit.

Defaults (every value can be overridden by an environment variable):
    QUANTMINE_DB_HOST / QUANTMINE_DB_PORT   default localhost / 5432
    QUANTMINE_DB_NAME                       default quantmine
    QUANTMINE_AIRFLOW_DB                    default airflow
    QUANTMINE_SUPERUSER_URL                 default postgresql://postgres@localhost:5432/postgres
    QUANTMINE_ADMIN_USER / _PASSWORD        administrator credentials. The user
                                            name defaults to admin; an empty
                                            password is generated randomly,
                                            printed once and written to
                                            .initial-credentials.json

Forgotten password: scripts/reset_password.py <username> (hashes are one-way,
so the only recovery path is a reset).

Usage:
    webapi/.venv/bin/python scripts/setup.py            # interactive
    webapi/.venv/bin/python scripts/setup.py --yes      # non-interactive (with the two variables above)
    webapi/.venv/bin/python scripts/setup.py --skip-airflow
"""

from __future__ import annotations

import getpass
import os
import re
import secrets
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEBAPI = ROOT / "webapi"
# 让 app.*（security / auth db）可被 import——app 包在 webapi/ 下
if str(WEBAPI) not in sys.path:
    sys.path.insert(0, str(WEBAPI))

# ----------------------------------------------------------------------------
# 默认值（环境变量可覆盖）
# ----------------------------------------------------------------------------
DB_HOST = os.environ.get("QUANTMINE_DB_HOST", "localhost")
DB_PORT = os.environ.get("QUANTMINE_DB_PORT", "5432")
APP_DB = os.environ.get("QUANTMINE_DB_NAME", "quantmine")
AIRFLOW_DB = os.environ.get("QUANTMINE_AIRFLOW_DB", "airflow")
WEB_ROLE = "quantmine_web"
PIPE_ROLE = "quantmine_pipeline"
AIRFLOW_ROLE = "airflow"
SUPER_URL = os.environ.get(
    "QUANTMINE_SUPERUSER_URL", f"postgresql://postgres@{DB_HOST}:{DB_PORT}/postgres"
)
ENV_PATH = ROOT / ".env"
SCHEMA_SQL = ROOT / "quantmine" / "storage" / "schema.sql"
AIRFLOW_HOME = os.environ.get("AIRFLOW_HOME", str(ROOT / "airflow"))
AIRFLOW_BIN = os.environ.get("QUANT_AIRFLOW_BIN", str(ROOT / ".venv" / "bin" / "airflow"))


def _log(msg: str) -> None:
    print(f"[setup] {msg}")


# ----------------------------------------------------------------------------
# 生成的登录凭据
#
# 不设固定默认密码（admin/admin 这类）。部署一跑完账号就能用，但密码是随机的，
# 所以扫描器猜不到，也不存在"忘了改默认密码"这个失败模式——Airflow 早年的
# admin/admin 快速上手指引正是大量实例被打穿的原因，这里不重蹈。
#
# 只在本次运行真正新建了账号时才记录：账号已存在时若还打印一个新生成的密码，
# 那密码根本没写进库，反而误导。
# ----------------------------------------------------------------------------
DEFAULT_ADMIN_USER = "admin"
DEFAULT_WEB_URL = "http://localhost:5173"
DEFAULT_AIRFLOW_URL = "http://localhost:8080"

_generated: list[dict] = []


def _record_credential(
    service: str, username: str, password: str, url: str = ""
) -> None:
    """Record one credential created by this run; _flush_credentials persists
    and prints the whole batch."""
    _generated.append(
        {"service": service, "url": url, "username": username, "password": password}
    )


def _flush_credentials() -> None:
    """Write the credentials generated by this run to .initial-credentials.json
    and print them once."""
    from _credentials import emit

    emit(_generated)


def _fail(msg: str) -> "NoReturn":  # type: ignore[name-defined]
    print(f"[setup] error: {msg}", file=sys.stderr)
    sys.exit(1)


# ----------------------------------------------------------------------------
# 超级用户后端：连接串直连 or sudo -u postgres，二者自动回退
# ----------------------------------------------------------------------------
class Superuser:
    def __init__(self) -> None:
        self.mode: str | None = None  # 'dsn' | 'sudo' | None

    @staticmethod
    def _pg_url(base: str, dbname: str) -> str:
        """Swap the database name in a connection string for dbname, dropping
        SQLAlchemy's +psycopg2 dialect suffix along the way."""
        base = base.replace("+psycopg2", "")
        return re.sub(r"/[^/?]*(\?.*)?$", f"/{dbname}", base)

    def probe(self) -> None:
        # 1) 直连
        try:
            import psycopg2  # noqa: F401

            conn = __import__("psycopg2").connect(self._pg_url(SUPER_URL, "postgres"))
            conn.close()
            self.mode = "dsn"
            _log("superuser access: direct connection string")
            return
        except Exception as exc:  # noqa: BLE001
            _log(f"direct connection unavailable ({type(exc).__name__}), trying sudo -u postgres ...")
        # 2) sudo psql
        try:
            proc = subprocess.run(
                ["sudo", "-u", "postgres", "psql", "-tAc", "select 1"],
                capture_output=True, text=True, timeout=60,
            )
            if proc.returncode == 0:
                self.mode = "sudo"
                _log("superuser access: sudo -u postgres psql")
                return
        except Exception:  # noqa: BLE001
            pass
        self.mode = None

    def exec(self, sql: str, dbname: str = "postgres") -> None:
        if self.mode == "dsn":
            import psycopg2

            conn = psycopg2.connect(self._pg_url(SUPER_URL, dbname))
            conn.autocommit = True  # CREATE DATABASE 不能在事务中
            try:
                with conn.cursor() as cur:
                    cur.execute(sql)
            finally:
                conn.close()
        elif self.mode == "sudo":
            proc = subprocess.run(
                ["sudo", "-u", "postgres", "psql", "-v", "ON_ERROR_STOP=1", "-d", dbname],
                input=sql, capture_output=True, text=True,
            )
            if proc.returncode != 0:
                raise RuntimeError(proc.stderr.strip() or proc.stdout.strip())
        else:
            raise RuntimeError("no superuser access")

    def scalar(self, sql: str, dbname: str = "postgres") -> str | None:
        if self.mode == "dsn":
            import psycopg2

            conn = psycopg2.connect(self._pg_url(SUPER_URL, dbname))
            try:
                with conn.cursor() as cur:
                    cur.execute(sql)
                    row = cur.fetchone()
                    return None if row is None else str(row[0])
            finally:
                conn.close()
        elif self.mode == "sudo":
            proc = subprocess.run(
                ["sudo", "-u", "postgres", "psql", "-tAc", sql, "-d", dbname],
                capture_output=True, text=True,
            )
            if proc.returncode != 0:
                raise RuntimeError(proc.stderr.strip())
            out = proc.stdout.strip()
            return out or None
        raise RuntimeError("no superuser access")


# ----------------------------------------------------------------------------
# .env 读写（只增/改受管键，保留其它行；修正结尾换行）
# ----------------------------------------------------------------------------
def read_env() -> dict[str, str]:
    values: dict[str, str] = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            values[key.strip()] = val.strip()
    return values


def write_env(updates: dict[str, str]) -> None:
    """Merge updates into .env: rewrite existing keys, append missing ones, and
    leave every other line untouched."""
    lines: list[str] = []
    seen: set[str] = set()
    existing = ENV_PATH.read_text(encoding="utf-8").splitlines() if ENV_PATH.exists() else []
    for line in existing:
        stripped = line.strip()
        if "=" in stripped and not stripped.startswith("#"):
            key = stripped.partition("=")[0].strip()
            if key in updates:
                lines.append(f"{key}={updates[key]}")
                seen.add(key)
                continue
        lines.append(line)
    for key, val in updates.items():
        if key not in seen:
            lines.append(f"{key}={val}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")  # 保证结尾换行


def _password_from_url(url: str | None) -> str | None:
    if not url:
        return None
    match = re.search(r"://[^:/@]+:([^@]+)@", url)
    return match.group(1) if match else None


def _build_url(role: str, password: str, dbname: str, *, sqlalchemy: bool = True) -> str:
    scheme = "postgresql+psycopg2" if sqlalchemy else "postgresql"
    return f"{scheme}://{role}:{password}@{DB_HOST}:{DB_PORT}/{dbname}"


# ----------------------------------------------------------------------------
# 各步骤
# ----------------------------------------------------------------------------
def ensure_role(su: Superuser, name: str, password: str) -> None:
    """Create the role if it is missing; if it exists, align its password with
    the value we manage so .env and the database stay consistent."""
    exists = su.scalar(f"SELECT 1 FROM pg_roles WHERE rolname = '{name}'")
    if exists:
        su.exec(f"ALTER ROLE {name} WITH LOGIN PASSWORD '{password}'")
        _log(f"role already exists, password aligned: {name}")
    else:
        su.exec(f"CREATE ROLE {name} WITH LOGIN PASSWORD '{password}'")
        _log(f"role created: {name}")


def ensure_database(su: Superuser, name: str, owner: str) -> None:
    exists = su.scalar(f"SELECT 1 FROM pg_database WHERE datname = '{name}'")
    if exists:
        _log(f"database already exists: {name}")
    else:
        su.exec(f'CREATE DATABASE "{name}" OWNER {owner}')
        _log(f"database created: {name} (owner={owner})")


def apply_schema(su: Superuser) -> None:
    """Apply schema.sql, the single source of truth for table creation.

    schema.sql is idempotent throughout (CREATE EXTENSION / TABLE / INDEX all
    carry IF NOT EXISTS), so it is replayed unconditionally: a fresh database
    gets everything, an existing one only gains the missing objects.
    """
    su.exec(SCHEMA_SQL.read_text(encoding="utf-8"), dbname=APP_DB)
    _log("schema.sql applied (including the pgvector extension)")


def grant_privileges(su: Superuser) -> None:
    """schema.sql carries no GRANTs, so least-privilege roles are granted here,
    including default privileges for tables created later."""
    web_write_tables = (
        "auth_users, report_history, interaction_logs, ai_conversations, "
        "ai_messages, ai_message_embeddings, ai_attachments, ai_config"
    )
    su.exec(
        f"""
        GRANT USAGE ON SCHEMA public TO {WEB_ROLE}, {PIPE_ROLE};
        REVOKE INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM {WEB_ROLE};
        GRANT SELECT ON ALL TABLES IN SCHEMA public TO {WEB_ROLE};
        GRANT SELECT, INSERT, UPDATE, DELETE ON {web_write_tables} TO {WEB_ROLE};
        GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {PIPE_ROLE};
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {WEB_ROLE}, {PIPE_ROLE};
        ALTER DEFAULT PRIVILEGES IN SCHEMA public
            REVOKE INSERT, UPDATE, DELETE ON TABLES FROM {WEB_ROLE};
        ALTER DEFAULT PRIVILEGES IN SCHEMA public
            GRANT SELECT ON TABLES TO {WEB_ROLE};
        ALTER DEFAULT PRIVILEGES IN SCHEMA public
            GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {PIPE_ROLE};
        ALTER DEFAULT PRIVILEGES IN SCHEMA public
            GRANT USAGE, SELECT ON SEQUENCES TO {WEB_ROLE}, {PIPE_ROLE};
        """,
        dbname=APP_DB,
    )
    _log("granted web writes on application tables and pipeline writes on all tables")


def init_airflow(airflow_dsn: str) -> None:
    if not Path(AIRFLOW_BIN).exists():
        _log(f"airflow executable not found ({AIRFLOW_BIN}), skipping Airflow initialization."
             " Set QUANT_AIRFLOW_BIN to point at it, or run `airflow db migrate` by hand later.")
        return
    env = dict(os.environ)
    env["AIRFLOW_HOME"] = AIRFLOW_HOME
    # airflow 用 sqlalchemy，接受 postgresql:// 前缀
    env["AIRFLOW__DATABASE__SQL_ALCHEMY_CONN"] = airflow_dsn
    env["AIRFLOW__CORE__SQL_ALCHEMY_CONN"] = airflow_dsn
    try:
        subprocess.run([AIRFLOW_BIN, "db", "migrate"], env=env, check=True, timeout=300)
        _log("Airflow metadata database initialized")
        # 建内部 admin。密码随机而非硬编码 airflow/airflow：Airflow UI 一旦从本机
        # 挪到内网以外，固定凭据就是现成的入口。
        # 密码经 argv 传递，同机其它用户能从 ps 看到——面向个人自托管可接受，
        # 换 --use-random-password 则要解析 Airflow 的输出，跨版本更脆。
        password = secrets.token_urlsafe(18)
        created = subprocess.run(
            [AIRFLOW_BIN, "users", "create", "--username", "airflow", "--password",
             password, "--firstname", "Admin", "--lastname", "User", "--role",
             "Admin", "--email", "admin@example.com"],
            env=env, capture_output=True, text=True, timeout=120,
        )
        if created.returncode == 0:
            _record_credential(
                "Airflow UI", "airflow", password, DEFAULT_AIRFLOW_URL
            )
            _log("Airflow internal admin created")
        else:
            # 非零退出几乎都是"用户已存在"，此时上面这个密码没生效，不能记录
            _log("Airflow internal admin already exists, keeping its current password")
    except Exception as exc:  # noqa: BLE001
        _log(f"Airflow initialization incomplete ({type(exc).__name__}: {exc}) -- login, research"
             " and reports are unaffected; re-run when the Workflows page needs it.")


def create_admin(web_url: str, *, non_interactive: bool) -> None:
    """Guarantee that one administrator account can log in.

    This step is never skipped. The backend exposes no registration endpoint and
    the login page gates every route except health and auth, so finishing setup
    with zero accounts means a deployment nobody can enter and no self-service
    way out. When credentials are absent we therefore create an account with the
    default user name and a random password instead of skipping.
    """
    from quantmine.storage.database import get_engine
    from app.api.v1.auth.db import create_user, get_user_by_username

    username = os.environ.get("QUANTMINE_ADMIN_USER") or ""
    password = os.environ.get("QUANTMINE_ADMIN_PASSWORD") or ""

    if not username and not non_interactive:
        username = input(f"Administrator user name (Enter for {DEFAULT_ADMIN_USER}): ").strip()
        if not password:
            password = getpass.getpass("Administrator password (Enter to generate one): ")

    username = username or DEFAULT_ADMIN_USER
    generated = not password
    if generated:
        password = secrets.token_urlsafe(18)

    engine = get_engine(web_url)
    if get_user_by_username(engine, username):
        # 幂等重跑走这里。若刚生成了密码也不能记录：它没写进库。
        _log(f"administrator already exists, skipping: {username}")
        return

    create_user(engine, username=username, password=password, display_name="Administrator")
    _log(f"administrator created: {username}")
    if generated:
        _record_credential("quantmine", username, password, DEFAULT_WEB_URL)


# ----------------------------------------------------------------------------
# 主流程
# ----------------------------------------------------------------------------
def main(argv: list[str]) -> int:
    skip_airflow = "--skip-airflow" in argv
    non_interactive = "--yes" in argv

    if not SCHEMA_SQL.exists():
        _fail(f"schema.sql not found: {SCHEMA_SQL}")

    su = Superuser()
    su.probe()
    if su.mode is None:
        print(
            "\n[setup] Could not obtain Postgres superuser access. Run the following SQL as a"
            " superuser by hand, then re-run this script:\n"
            f"  CREATE ROLE {WEB_ROLE} LOGIN PASSWORD '<pw>';\n"
            f"  CREATE ROLE {PIPE_ROLE} LOGIN PASSWORD '<pw>';\n"
            f"  CREATE ROLE {AIRFLOW_ROLE} LOGIN PASSWORD '<pw>';\n"
            f"  CREATE DATABASE {APP_DB} OWNER {WEB_ROLE};\n"
            f"  CREATE DATABASE {AIRFLOW_DB} OWNER {AIRFLOW_ROLE};\n"
            "Alternatively, set QUANTMINE_SUPERUSER_URL to a working superuser connection string.",
            file=sys.stderr,
        )
        return 1

    # 1) 解析/生成各角色密码（优先复用现有 .env，保证重复运行一致）
    env_values = read_env()
    web_pw = _password_from_url(env_values.get("QUANTMINE_DATABASE_URL")) or secrets.token_hex(16)
    pipe_pw = _password_from_url(env_values.get("QUANTMINE_PIPELINE_DATABASE_URL")) or secrets.token_hex(16)
    airflow_pw = _password_from_url(env_values.get("QUANT_AIRFLOW_PG_DSN")) or secrets.token_hex(16)

    # 2) 角色 + 库
    ensure_role(su, WEB_ROLE, web_pw)
    ensure_role(su, PIPE_ROLE, pipe_pw)
    ensure_role(su, AIRFLOW_ROLE, airflow_pw)
    ensure_database(su, APP_DB, owner=WEB_ROLE)
    ensure_database(su, AIRFLOW_DB, owner=AIRFLOW_ROLE)

    # 3) 扩展 + schema + 授权
    apply_schema(su)
    grant_privileges(su)

    # 4) 写 .env（受管键）
    web_url = _build_url(WEB_ROLE, web_pw, APP_DB)
    pipe_url = _build_url(PIPE_ROLE, pipe_pw, APP_DB)
    airflow_dsn = _build_url(AIRFLOW_ROLE, airflow_pw, AIRFLOW_DB, sqlalchemy=False)
    updates = {
        "QUANTMINE_DATABASE_URL": web_url,
        "QUANTMINE_PIPELINE_DATABASE_URL": pipe_url,
        "QUANT_AIRFLOW_PG_DSN": airflow_dsn,
    }
    if not env_values.get("QUANT_AUTH_SECRET"):
        updates["QUANT_AUTH_SECRET"] = secrets.token_hex(32)
    write_env(updates)
    _log(".env written")

    # 5) Airflow（best-effort）
    if skip_airflow:
        _log("skipping Airflow initialization (--skip-airflow)")
    else:
        init_airflow(airflow_dsn)

    # 6) 管理员账号
    create_admin(web_url, non_interactive=non_interactive)

    _log("done. Start the backend (uvicorn) and frontend (vite), then sign in as the administrator.")
    # 放在完成日志之后：随机凭据是本次运行最需要被看到的一段输出
    _flush_credentials()
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
